### ISSUE TITLE
Reta Final

### ISSUE THREAD

**Issue by lucasliet** [lucasliet/ReciclaMais#2]
- [ ] Mais informações no **Como Separar**
- [ ] Gravar **vídeo** para o Como Separar @EloYoshida 
- [x] **Encontrar ícone** pra opção de outros nos descartes
- [x] Criar **Logo**
- [x] Textura de fundo
- [x] Opção de **outros** nos descartes disponiveis
- [x] Melhorar **responsividade** do Layout
- [x] **Separar página** com lista de locais sugeridos @lucasliet 
- [x] Separar campo de **Rua**, **Número** e **CEP** em endereço na página de **Sugestões**

**Comment by gustavobiel** [comment]
Tira o Mobile, carai

**Comment by lucasliet** [comment]
> Tira o Mobile, carai

Seja mais **educado** senhor, por obséquio

**Comment by EloYoshida** [comment]
![icones (1)](https://user-images.githubusercontent.com/50083455/68762155-61408980-05f4-11ea-8b70-b01f896c0f15.gif)
![simbolos reciclagem (1)](https://user-images.githubusercontent.com/50083455/68762159-6271b680-05f4-11ea-8346-2fb5d7df9892.jpg)

BOM DIA ! ALGUNS ÍCONES DE SUGESTÃO

**Comment by william-rm** [comment]
Dois exemplos de logo galera ! 
![Recicla+ Logo (1)](https://user-images.githubusercontent.com/56612734/68825713-dace8b00-0679-11ea-81be-d590dccb21d5.png)
![Recicla+ Logo](https://user-images.githubusercontent.com/56612734/68825714-dace8b00-0679-11ea-9564-3861e9a61cb7.png)

**Comment by EloYoshida** [comment]
Mais informações no Como Separar @william-rm  vc fez algo? sennao ja vou fazer aqui....

**Comment by william-rm** [comment]
Não elo , ainda não mexi

**Comment by lucasliet** [comment]
> 
> 
> ![icones (1)](https://user-images.githubusercontent.com/50083455/68762155-61408980-05f4-11ea-8b70-b01f896c0f15.gif)
> ![simbolos reciclagem (1)](https://user-images.githubusercontent.com/50083455/68762159-6271b680-05f4-11ea-8346-2fb5d7df9892.jpg)
> 
> BOM DIA ! ALGUNS ÍCONES DE SUGESTÃO

Curti bastante as informações aqui, da pra colocar no como separar, mas não como uma imagem única porque não vai ficar responsivo

**Comment by EloYoshida** [comment]
achei super bonito novo ícone

**Comment by EloYoshida** [comment]
acho que por hora podemos deixar este video ...... 
https://youtu.be/QZojaujbDpw
